export const allEmployees = [
  {
    name: 'Judye Clowton',
    designation: 'UI Specialist',
    technologies: ['Angular'],
    skills: ['UX'],
    availability: 1,
    baseLocation: 'Pune',
    currentLocation: 'Bengaluru',
    openToRelocate: true,
  },
  {
    name: 'Briggs Selly',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 2,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Tomaso Beardshaw',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 3,
    baseLocation: 'Indore',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Nedda Cudworth',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 4,
    baseLocation: 'Bengaluru',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Fitz Metts',
    designation: 'Senior UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 5,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Reece Harken',
    designation: 'Senior UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UX'],
    availability: 6,
    baseLocation: 'Pune',
    currentLocation: 'Bengaluru',
    openToRelocate: false,
  },
  {
    name: 'Tony Veschambes',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UX'],
    availability: 7,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Errick Ballham',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UX'],
    availability: 8,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Kimbell Iczokvitz',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 9,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Peggie Bedson',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 10,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Celestine Webber',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 11,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Violet Baudins',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 12,
    baseLocation: 'Hyderabad',
    currentLocation: 'Indore',
    openToRelocate: true,
  },
  {
    name: 'Ansel Borland',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 13,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Evelina Rivenzon',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 14,
    baseLocation: 'Pune',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Bob MacGauhy',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 15,
    baseLocation: 'Pune',
    currentLocation: 'Bengaluru',
    openToRelocate: true,
  },
  {
    name: 'Rachael Duckwith',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 16,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Sioux Huguet',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 17,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Alexi Samuels',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 18,
    baseLocation: 'Indore',
    currentLocation: 'Hyderabad',
    openToRelocate: true,
  },
  {
    name: 'Glenn Donohoe',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 19,
    baseLocation: 'Bengaluru',
    currentLocation: 'Pune',
    openToRelocate: false,
  },
  {
    name: 'Bondy Goodison',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 20,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Elihu Lymbourne',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI'],
    availability: 21,
    baseLocation: 'Hyderabad',
    currentLocation: 'Indore',
    openToRelocate: true,
  },
  {
    name: 'Moria Moylane',
    designation: 'UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 22,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Horacio Figurski',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 23,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Paquito Fossett',
    designation: 'UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 24,
    baseLocation: 'Bengaluru',
    currentLocation: 'Indore',
    openToRelocate: true,
  },
  {
    name: 'Jessika Janaud',
    designation: 'UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 25,
    baseLocation: 'Indore',
    currentLocation: 'Pune',
    openToRelocate: false,
  },
  {
    name: 'Modestia Berrigan',
    designation: 'Senior UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 26,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Kaine Worling',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 27,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Corny Finch',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 28,
    baseLocation: 'Pune',
    currentLocation: 'Hyderabad',
    openToRelocate: false,
  },
  {
    name: 'Irvin Emeney',
    designation: 'Associate UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI'],
    availability: 29,
    baseLocation: 'Pune',
    currentLocation: 'Bengaluru',
    openToRelocate: false,
  },
  {
    name: 'Lezlie Duckels',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 30,
    baseLocation: 'Hyderabad',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Kaia Hardiker',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 31,
    baseLocation: 'Pune',
    currentLocation: 'Hyderabad',
    openToRelocate: false,
  },
  {
    name: 'Arch Coon',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 32,
    baseLocation: 'Bengaluru',
    currentLocation: 'Hyderabad',
    openToRelocate: true,
  },
  {
    name: 'Gerrie Thornally',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 33,
    baseLocation: 'Pune',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Holly Starbeck',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 34,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Quinn Kliemann',
    designation: 'Lead UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI'],
    availability: 35,
    baseLocation: 'Pune',
    currentLocation: 'Pune',
    openToRelocate: false,
  },
  {
    name: 'Kaine Binnell',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 36,
    baseLocation: 'Bengaluru',
    currentLocation: 'Indore',
    openToRelocate: true,
  },
  {
    name: 'Anallese McTeggart',
    designation: 'UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 37,
    baseLocation: 'Indore',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Kristan Vogeller',
    designation: 'Associate UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI'],
    availability: 38,
    baseLocation: 'Pune',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Eileen Glashby',
    designation: 'Associate UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UX'],
    availability: 39,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Janey Snalum',
    designation: 'Senior UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 40,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Guendolen Bere',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 41,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Kissie Oliphard',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 42,
    baseLocation: 'Hyderabad',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Alisun Rudham',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 43,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Keir Woodier',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 44,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Jeremiah Weigh',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 45,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Rosmunda Loges',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 46,
    baseLocation: 'Hyderabad',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Arlyne Glitherow',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 47,
    baseLocation: 'Hyderabad',
    currentLocation: 'Bengaluru',
    openToRelocate: true,
  },
  {
    name: 'Camala Giaomozzo',
    designation: 'Senior UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 48,
    baseLocation: 'Bengaluru',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Roxy Sneesby',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI'],
    availability: 49,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Jamima Drillot',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UX'],
    availability: 50,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Prisca Lundy',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 51,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Cassi Winscomb',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 52,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Barde Merredy',
    designation: 'Lead UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UX'],
    availability: 53,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Wesley Worsalls',
    designation: 'UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 54,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Alleyn Fullun',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 55,
    baseLocation: 'Pune',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Dniren Cammock',
    designation: 'UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 56,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Bealle de Almeida',
    designation: 'Associate UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 57,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Petr MacDonogh',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 58,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Normand Dugmore',
    designation: 'UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI'],
    availability: 59,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Doe MacNeilly',
    designation: 'UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UX'],
    availability: 60,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Juliana Blackborne',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 61,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Garrett Barneveld',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 62,
    baseLocation: 'Pune',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Marget Geall',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 63,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Hubert Antrack',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 64,
    baseLocation: 'Bengaluru',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Fransisco Baumaier',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 65,
    baseLocation: 'Bengaluru',
    currentLocation: 'Pune',
    openToRelocate: true,
  },
  {
    name: 'Ogdon McCreery',
    designation: 'Associate UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UX'],
    availability: 66,
    baseLocation: 'Indore',
    currentLocation: 'Bengaluru',
    openToRelocate: false,
  },
  {
    name: 'Laina Brahan',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 67,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Esme Beckitt',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 68,
    baseLocation: 'Hyderabad',
    currentLocation: 'Hyderabad',
    openToRelocate: false,
  },
  {
    name: 'Andrei Ivashinnikov',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 69,
    baseLocation: 'Pune',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Candice Poulsum',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 70,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Antoni Viles',
    designation: 'UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI'],
    availability: 71,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Wanids Flanaghan',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UX'],
    availability: 72,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: "Esme O' Carrol",
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI'],
    availability: 73,
    baseLocation: 'Bengaluru',
    currentLocation: 'Bengaluru',
    openToRelocate: true,
  },
  {
    name: 'Myrta Faivre',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 74,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Mechelle Yeld',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UX'],
    availability: 75,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Culver Darnody',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 76,
    baseLocation: 'Pune',
    currentLocation: 'Bengaluru',
    openToRelocate: true,
  },
  {
    name: 'Brittaney Iacobacci',
    designation: 'Lead UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UX'],
    availability: 77,
    baseLocation: 'Indore',
    currentLocation: 'Bengaluru',
    openToRelocate: true,
  },
  {
    name: 'Indira Aykroyd',
    designation: 'Lead UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 78,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Charmaine Taffurelli',
    designation: 'UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 79,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Polly McManamon',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 80,
    baseLocation: 'Pune',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Randy Speachley',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 81,
    baseLocation: 'Bengaluru',
    currentLocation: 'Bengaluru',
    openToRelocate: false,
  },
  {
    name: 'Carolin Furley',
    designation: 'Associate UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 82,
    baseLocation: 'Hyderabad',
    currentLocation: 'Indore',
    openToRelocate: true,
  },
  {
    name: 'Stewart Slater',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UI', 'UX'],
    availability: 83,
    baseLocation: 'Pune',
    currentLocation: 'Hyderabad',
    openToRelocate: true,
  },
  {
    name: 'Mady Hasslocher',
    designation: 'Senior UI Specialist',
    technologies: ['React', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 84,
    baseLocation: 'Pune',
    currentLocation: 'Indore',
    openToRelocate: false,
  },
  {
    name: 'Zelda Fontin',
    designation: 'UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 85,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Donella Faulconer',
    designation: 'Associate UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 86,
    baseLocation: 'Pune',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Rock Emmins',
    designation: 'UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 87,
    baseLocation: 'Bengaluru',
    currentLocation: 'Hyderabad',
    openToRelocate: true,
  },
  {
    name: 'Stacy Shieber',
    designation: 'UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 88,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Tyne Toomer',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 89,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: "Perl O' Scollee",
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI', 'UX'],
    availability: 90,
    baseLocation: 'Bengaluru',
    currentLocation: 'Pune',
    openToRelocate: false,
  },
  {
    name: 'Minerva Parres',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 91,
    baseLocation: 'Hyderabad',
    currentLocation: 'Hyderabad',
    openToRelocate: false,
  },
  {
    name: 'Brook Schroter',
    designation: 'Associate UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 92,
    baseLocation: 'Hyderabad',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Gabby Smewings',
    designation: 'UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 93,
    baseLocation: 'Hyderabad',
    currentLocation: 'Bengaluru',
    openToRelocate: false,
  },
  {
    name: 'Tamiko Vasnetsov',
    designation: 'UI Specialist',
    technologies: ['Angular', 'React'],
    skills: ['UX'],
    availability: 94,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Ike Fosberry',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UX'],
    availability: 95,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Fred Spanswick',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UI', 'UX'],
    availability: 96,
    baseLocation: 'Bengaluru',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Kellia Bodemeaid',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'React', 'Vue'],
    skills: ['UX'],
    availability: 97,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: false,
  },
  {
    name: 'Rochette Ringer',
    designation: 'Senior UI Specialist',
    technologies: ['Angular'],
    skills: ['UX'],
    availability: 98,
    baseLocation: 'Pune',
    currentLocation: 'Hyderabad',
    openToRelocate: true,
  },
  {
    name: 'Tisha Weatherall',
    designation: 'Senior UI Specialist',
    technologies: ['Angular', 'Vue'],
    skills: ['UI'],
    availability: 99,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: true,
  },
  {
    name: 'Yovonnda Brittlebank',
    designation: 'Lead UI Specialist',
    technologies: ['Angular'],
    skills: ['UI'],
    availability: 100,
    baseLocation: 'Indore',
    currentLocation: null,
    openToRelocate: true,
  },
];

export const allLocations = [
  'Pune',
  'Indore',
  'Bengaluru',
  'Hyderabad',
  'Delhi',
  'Gurgaon',
  'Chennai',
  'Mumbai',
];

export const allTechnologies = ['Angular', 'React', 'Vue'];

export const allSkills = ['UI', 'UX'];
